/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#ifndef QML_SPRK_PLUGIN_H
#define QML_SPRK_PLUGIN_H

#include <QQmlExtensionPlugin>
#include <qqml.h>

class QmlSprkCtx;
class QmlSprkCtxAttached;
class QmlSprkDataset;
class QmlSprkDatasetAttached;
class QmlSprkBlock;
class QmlSprkBlockAttached;
class QmlSprkBlockdata;
class QmlSprkBlockdataAttached;
class QmlSprkDescriptor;
class QmlSprkDescriptorAttached;
class QmlSprkTransform;
class QmlSprkTransformAttached;
class QmlSprkBlockManager;
class QmlSprkBlockManagerAttached;

#include "QmlSprkCtx.h"
#include "QmlSprkDataset.h"
#include "QmlSprkBlock.h"
#include "QmlSprkBlockdata.h"
#include "QmlSprkDescriptor.h"
#include "QmlSprkTransform.h"
#include "QmlSprkBlockManager.h"

class QmlSprkPlugin : public QQmlExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA (IID "org.qt-project.Qt.QQmlExtensionInterface")
    
public:
    void registerTypes (const char *uri)
    {
        qmlRegisterType<QmlSprkCtx> (uri, 1, 0, "QmlSprkCtx");
        qmlRegisterType<QmlSprkCtxAttached>();
        qmlRegisterType<QmlSprkDataset> (uri, 1, 0, "QmlSprkDataset");
        qmlRegisterType<QmlSprkDatasetAttached>();
        qmlRegisterType<QmlSprkBlock> (uri, 1, 0, "QmlSprkBlock");
        qmlRegisterType<QmlSprkBlockAttached>();
        qmlRegisterType<QmlSprkBlockdata> (uri, 1, 0, "QmlSprkBlockdata");
        qmlRegisterType<QmlSprkBlockdataAttached>();
        qmlRegisterType<QmlSprkDescriptor> (uri, 1, 0, "QmlSprkDescriptor");
        qmlRegisterType<QmlSprkDescriptorAttached>();
        qmlRegisterType<QmlSprkTransform> (uri, 1, 0, "QmlSprkTransform");
        qmlRegisterType<QmlSprkTransformAttached>();
        qmlRegisterType<QmlSprkBlockManager> (uri, 1, 0, "QmlSprkBlockManager");
        qmlRegisterType<QmlSprkBlockManagerAttached>();
    };
};

#endif

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
