/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "QmlBlock.h"


///
//  Queue a transformation to be applied to this block.
void QmlBlock::queueTransform (transformation_t *transform) {
    block_queue_transform (self, transform);
};


QObject* QmlBlock::qmlAttachedProperties(QObject* object) {
    return new QmlBlockAttached(object);
}


///
//  Self test of this class.
void QmlBlockAttached::test (bool verbose) {
    block_test (verbose);
};

///
//  Creates a new block
QmlBlock *QmlBlockAttached::construct (const QString &blockId, QmlDescriptor *descriptor, zlist_t *appliedTransforms) {
    QmlBlock *qmlSelf = new QmlBlock ();
    qmlSelf->self = block_new (blockId.toUtf8().data(), descriptor->self, appliedTransforms);
    return qmlSelf;
};

///
//  Destroy the block.
void QmlBlockAttached::destruct (QmlBlock *qmlSelf) {
    block_destroy (&qmlSelf->self);
};

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
