/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "QmlDescriptor.h"



QObject* QmlDescriptor::qmlAttachedProperties(QObject* object) {
    return new QmlDescriptorAttached(object);
}


///
//  Self test of this class.
void QmlDescriptorAttached::test (bool verbose) {
    descriptor_test (verbose);
};

///
//  Creates a new descriptor.
QmlDescriptor *QmlDescriptorAttached::construct () {
    QmlDescriptor *qmlSelf = new QmlDescriptor ();
    qmlSelf->self = descriptor_new ();
    return qmlSelf;
};

///
//  Destroy the descriptor.
void QmlDescriptorAttached::destruct (QmlDescriptor *qmlSelf) {
    descriptor_destroy (&qmlSelf->self);
};

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
