/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#ifndef QML_DESCRIPTOR_H
#define QML_DESCRIPTOR_H

#include <QtQml>

#include <sprk.h>
#include "qml_sprk_plugin.h"


class QmlDescriptor : public QObject
{
    Q_OBJECT
    Q_PROPERTY(bool isNULL READ isNULL)
    
public:
    descriptor_t *self;
    
    QmlDescriptor() { self = NULL; }
    bool isNULL() { return self == NULL; }
    
    static QObject* qmlAttachedProperties(QObject* object); // defined in QmlDescriptor.cpp
    
public slots:};

class QmlDescriptorAttached : public QObject
{
    Q_OBJECT
    QObject* m_attached;
    
public:
    QmlDescriptorAttached (QObject* attached) {
        Q_UNUSED (attached);
    };
    
public slots:
    //  Self test of this class.
    void test (bool verbose);

    //  Creates a new descriptor.
    QmlDescriptor *construct ();

    //  Destroy the descriptor.
    void destruct (QmlDescriptor *qmlSelf);
};


QML_DECLARE_TYPEINFO(QmlDescriptor, QML_HAS_ATTACHED_PROPERTIES)

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
