/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "QmlSprkMsg.h"



QObject* QmlSprkMsg::qmlAttachedProperties(QObject* object) {
    return new QmlSprkMsgAttached(object);
}


///
//  Self test of this class.
void QmlSprkMsgAttached::test (bool verbose) {
    sprk_msg_test (verbose);
};

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
