/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "QmlSprkTransform.h"



QObject* QmlSprkTransform::qmlAttachedProperties(QObject* object) {
    return new QmlSprkTransformAttached(object);
}


///
//  Self test of this class.
void QmlSprkTransformAttached::test (bool verbose) {
    sprk_transform_test (verbose);
};

///
//  Creates a new transformation.
QmlSprkTransform *QmlSprkTransformAttached::construct () {
    QmlSprkTransform *qmlSelf = new QmlSprkTransform ();
    qmlSelf->self = sprk_transform_new ();
    return qmlSelf;
};

///
//  Destroy the sprk_transform.
void QmlSprkTransformAttached::destruct (QmlSprkTransform *qmlSelf) {
    sprk_transform_destroy (&qmlSelf->self);
};

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
