/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#ifndef QML_SPRK_BLOCKDATA_H
#define QML_SPRK_BLOCKDATA_H

#include <QtQml>

#include <sprk.h>
#include "qml_sprk_plugin.h"


class QmlSprkBlockdata : public QObject
{
    Q_OBJECT
    Q_PROPERTY(bool isNULL READ isNULL)
    
public:
    sprk_blockdata_t *self;
    
    QmlSprkBlockdata() { self = NULL; }
    bool isNULL() { return self == NULL; }
    
    static QObject* qmlAttachedProperties(QObject* object); // defined in QmlSprkBlockdata.cpp
    
public slots:
    //  Queue a transformation to be applied to this block.
    void queueTransform (QmlSprkTransform *transform);

    //  
    QmlSprkDescriptor *descriptor ();
};

class QmlSprkBlockdataAttached : public QObject
{
    Q_OBJECT
    QObject* m_attached;
    
public:
    QmlSprkBlockdataAttached (QObject* attached) {
        Q_UNUSED (attached);
    };
    
public slots:
    //  Self test of this class.
    void test (bool verbose);

    //  Create a new sprk_blockdata.
    QmlSprkBlockdata *construct (QmlSprkBlock *block, float*data, uint32_t length);

    //  Destroy the sprk_blockdata.
    void destruct (QmlSprkBlockdata *qmlSelf);
};


QML_DECLARE_TYPEINFO(QmlSprkBlockdata, QML_HAS_ATTACHED_PROPERTIES)

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
