/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "QmlSprkCtx.h"


///
//  Assign a block to the executor pool, giving it a unique ID.
const QString QmlSprkCtx::assignBlock (QmlSprkBlock *block) {
    return QString (sprk_ctx_assign_block (self, block->self));
};

///
//  Remove a block from the executor pool.
void QmlSprkCtx::dropBlock (QmlSprkBlock *block) {
    sprk_ctx_drop_block (self, block->self);
};


QObject* QmlSprkCtx::qmlAttachedProperties(QObject* object) {
    return new QmlSprkCtxAttached(object);
}


///
//  Self test of this class.
void QmlSprkCtxAttached::test (bool verbose) {
    sprk_ctx_test (verbose);
};

///
//  Creates a new sprk context which facilitates communication with
//  known executors.                                               
QmlSprkCtx *QmlSprkCtxAttached::construct () {
    QmlSprkCtx *qmlSelf = new QmlSprkCtx ();
    qmlSelf->self = sprk_ctx_new ();
    return qmlSelf;
};

///
//  Destroy the sprk_ctx.
void QmlSprkCtxAttached::destruct (QmlSprkCtx *qmlSelf) {
    sprk_ctx_destroy (&qmlSelf->self);
};

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
