/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#ifndef QML_SPRK_TRANSFORM_H
#define QML_SPRK_TRANSFORM_H

#include <QtQml>

#include <sprk.h>
#include "qml_sprk_plugin.h"


class QmlSprkTransform : public QObject
{
    Q_OBJECT
    Q_PROPERTY(bool isNULL READ isNULL)
    
public:
    sprk_transform_t *self;
    
    QmlSprkTransform() { self = NULL; }
    bool isNULL() { return self == NULL; }
    
    static QObject* qmlAttachedProperties(QObject* object); // defined in QmlSprkTransform.cpp
    
public slots:};

class QmlSprkTransformAttached : public QObject
{
    Q_OBJECT
    QObject* m_attached;
    
public:
    QmlSprkTransformAttached (QObject* attached) {
        Q_UNUSED (attached);
    };
    
public slots:
    //  Self test of this class.
    void test (bool verbose);

    //  Creates a new transformation.
    QmlSprkTransform *construct ();

    //  Destroy the sprk_transform.
    void destruct (QmlSprkTransform *qmlSelf);
};


QML_DECLARE_TYPEINFO(QmlSprkTransform, QML_HAS_ATTACHED_PROPERTIES)

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
