/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "QmlSprkDescriptor.h"


///
//  
const QString QmlSprkDescriptor::uri () {
    return QString (sprk_descriptor_uri (self));
};

///
//  
uint64_t QmlSprkDescriptor::offset () {
    return sprk_descriptor_offset (self);
};

///
//  
uint64_t QmlSprkDescriptor::length () {
    return sprk_descriptor_length (self);
};

///
//  
uint32_t QmlSprkDescriptor::rowSize () {
    return sprk_descriptor_row_size (self);
};


QObject* QmlSprkDescriptor::qmlAttachedProperties(QObject* object) {
    return new QmlSprkDescriptorAttached(object);
}


///
//  Self test of this class.
void QmlSprkDescriptorAttached::test (bool verbose) {
    sprk_descriptor_test (verbose);
};

///
//  Creates a new descriptor.
//  Creates a new descriptor.
QmlSprkDescriptor *QmlSprkDescriptorAttached::construct (const QString &uri, uint64_t offset, uint64_t length, uint32_t rowSize) {
    QmlSprkDescriptor *qmlSelf = new QmlSprkDescriptor ();
    qmlSelf->self = sprk_descriptor_new (uri.toUtf8().data(), offset, length, rowSize);
    return qmlSelf;
};

///
//  Destroy the sprk_descriptor.
void QmlSprkDescriptorAttached::destruct (QmlSprkDescriptor *qmlSelf) {
    sprk_descriptor_destroy (&qmlSelf->self);
};

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
