/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#ifndef QML_SPRK_BLOCK_MANAGER_H
#define QML_SPRK_BLOCK_MANAGER_H

#include <QtQml>

#include <sprk.h>
#include "qml_sprk_plugin.h"


class QmlSprkBlockManager : public QObject
{
    Q_OBJECT
    Q_PROPERTY(bool isNULL READ isNULL)
    
public:
    sprk_block_manager_t *self;
    
    QmlSprkBlockManager() { self = NULL; }
    bool isNULL() { return self == NULL; }
    
    static QObject* qmlAttachedProperties(QObject* object); // defined in QmlSprkBlockManager.cpp
    
public slots:
    //  
    sprk_blockdata_t *readAndStoreBlock (const QString &blockId, QmlSprkBlock *blockRef);

    //  
    sprk_blockdata_t *getBlock (const QString &blockId);
};

class QmlSprkBlockManagerAttached : public QObject
{
    Q_OBJECT
    QObject* m_attached;
    
public:
    QmlSprkBlockManagerAttached (QObject* attached) {
        Q_UNUSED (attached);
    };
    
public slots:
    //  Self test of this class.
    void test (bool verbose);

    //  Create a new block manager
    QmlSprkBlockManager *construct ();

    //  Destroy the block manager
    void destruct (QmlSprkBlockManager *qmlSelf);
};


QML_DECLARE_TYPEINFO(QmlSprkBlockManager, QML_HAS_ATTACHED_PROPERTIES)

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
