/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "QmlSprkBlockdata.h"


///
//  Queue a transformation to be applied to this block.
void QmlSprkBlockdata::queueTransform (QmlSprkTransform *transform) {
    sprk_blockdata_queue_transform (self, transform->self);
};

///
//  
QmlSprkDescriptor *QmlSprkBlockdata::descriptor () {
    QmlSprkDescriptor *retQ_ = new QmlSprkDescriptor ();
    retQ_->self = sprk_blockdata_descriptor (self);
    return retQ_;
};


QObject* QmlSprkBlockdata::qmlAttachedProperties(QObject* object) {
    return new QmlSprkBlockdataAttached(object);
}


///
//  Self test of this class.
void QmlSprkBlockdataAttached::test (bool verbose) {
    sprk_blockdata_test (verbose);
};

///
//  Create a new sprk_blockdata.
QmlSprkBlockdata *QmlSprkBlockdataAttached::construct (QmlSprkBlock *block, float*data, uint32_t length) {
    QmlSprkBlockdata *qmlSelf = new QmlSprkBlockdata ();
    qmlSelf->self = sprk_blockdata_new (block->self, data, length);
    return qmlSelf;
};

///
//  Destroy the sprk_blockdata.
void QmlSprkBlockdataAttached::destruct (QmlSprkBlockdata *qmlSelf) {
    sprk_blockdata_destroy (&qmlSelf->self);
};

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
