/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#ifndef QML_SPRK_BLOCK_H
#define QML_SPRK_BLOCK_H

#include <QtQml>

#include <sprk.h>
#include "qml_sprk_plugin.h"


class QmlSprkBlock : public QObject
{
    Q_OBJECT
    Q_PROPERTY(bool isNULL READ isNULL)
    
public:
    sprk_block_t *self;
    
    QmlSprkBlock() { self = NULL; }
    bool isNULL() { return self == NULL; }
    
    static QObject* qmlAttachedProperties(QObject* object); // defined in QmlSprkBlock.cpp
    
public slots:
    //  Queue a transformation to be applied to this block.
    void queueTransform (QmlSprkTransform *transform);

    //  
    QmlSprkDescriptor *descriptor ();
};

class QmlSprkBlockAttached : public QObject
{
    Q_OBJECT
    QObject* m_attached;
    
public:
    QmlSprkBlockAttached (QObject* attached) {
        Q_UNUSED (attached);
    };
    
public slots:
    //  Self test of this class.
    void test (bool verbose);

    //  Creates a new block
    QmlSprkBlock *construct (QmlSprkDescriptor *descriptor, zlist_t *appliedTransforms);

    //  Destroy the sprk_block.
    void destruct (QmlSprkBlock *qmlSelf);
};


QML_DECLARE_TYPEINFO(QmlSprkBlock, QML_HAS_ATTACHED_PROPERTIES)

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
