/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#ifndef QML_SPRK_DATASET_H
#define QML_SPRK_DATASET_H

#include <QtQml>

#include <sprk.h>
#include "qml_sprk_plugin.h"


class QmlSprkDataset : public QObject
{
    Q_OBJECT
    Q_PROPERTY(bool isNULL READ isNULL)
    
public:
    sprk_dataset_t *self;
    
    QmlSprkDataset() { self = NULL; }
    bool isNULL() { return self == NULL; }
    
    static QObject* qmlAttachedProperties(QObject* object); // defined in QmlSprkDataset.cpp
    
public slots:
    //  Checkpoints all blocks and their transformations across executors.
    void checkpoint ();

    //  Multiplies all values by the multiplier.
    void mul (float multiplier);

    //  Calculates the sum of all values in the dataset.
    float sum ();
};

class QmlSprkDatasetAttached : public QObject
{
    Q_OBJECT
    QObject* m_attached;
    
public:
    QmlSprkDatasetAttached (QObject* attached) {
        Q_UNUSED (attached);
    };
    
public slots:
    //  Self test of this class.
    void test (bool verbose);

    //  Destroy the sprk_dataset.
    void destruct (QmlSprkDataset *qmlSelf);
};


QML_DECLARE_TYPEINFO(QmlSprkDataset, QML_HAS_ATTACHED_PROPERTIES)

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
