/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "QmlSprkDescriptor.h"



QObject* QmlSprkDescriptor::qmlAttachedProperties(QObject* object) {
    return new QmlSprkDescriptorAttached(object);
}


///
//  Self test of this class.
void QmlSprkDescriptorAttached::test (bool verbose) {
    sprk_descriptor_test (verbose);
};

///
//  Creates a new descriptor.
QmlSprkDescriptor *QmlSprkDescriptorAttached::construct () {
    QmlSprkDescriptor *qmlSelf = new QmlSprkDescriptor ();
    qmlSelf->self = sprk_descriptor_new ();
    return qmlSelf;
};

///
//  Destroy the sprk_descriptor.
void QmlSprkDescriptorAttached::destruct (QmlSprkDescriptor *qmlSelf) {
    sprk_descriptor_destroy (&qmlSelf->self);
};

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
