/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "QmlTransformation.h"



QObject* QmlTransformation::qmlAttachedProperties(QObject* object) {
    return new QmlTransformationAttached(object);
}


///
//  Self test of this class.
void QmlTransformationAttached::test (bool verbose) {
    transformation_test (verbose);
};

///
//  Creates a new transformation.
QmlTransformation *QmlTransformationAttached::construct () {
    QmlTransformation *qmlSelf = new QmlTransformation ();
    qmlSelf->self = transformation_new ();
    return qmlSelf;
};

///
//  Destroy the transformation.
void QmlTransformationAttached::destruct (QmlTransformation *qmlSelf) {
    transformation_destroy (&qmlSelf->self);
};

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
