/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#ifndef Q_BLOCK_H
#define Q_BLOCK_H

#include "qsprk.h"

class QT_SPRK_EXPORT QBlock : public QObject
{
    Q_OBJECT
public:

    //  Copy-construct to return the proper wrapped c types
    QBlock (block_t *self, QObject *qObjParent = 0);

    //  Creates a new block
    explicit QBlock (const QString &blockId, QDescriptor *descriptor, zlist_t *appliedTransforms, QObject *qObjParent = 0);

    //  Destroy the block.
    ~QBlock ();

    //  Queue a transformation to be applied to this block.
    void queueTransform (transformation_t *transform);

    //  Self test of this class.
    static void test (bool verbose);

    block_t *self;
};
#endif //  Q_BLOCK_H
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
