/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "qsprk.h"

///
//  Copy-construct to return the proper wrapped c types
QBlock::QBlock (block_t *self, QObject *qObjParent) : QObject (qObjParent)
{
    this->self = self;
}


///
//  Creates a new block
QBlock::QBlock (const QString &blockId, QDescriptor *descriptor, zlist_t *appliedTransforms, QObject *qObjParent) : QObject (qObjParent)
{
    this->self = block_new (blockId.toUtf8().data(), descriptor->self, appliedTransforms);
}

///
//  Destroy the block.
QBlock::~QBlock ()
{
    block_destroy (&self);
}

///
//  Queue a transformation to be applied to this block.
void QBlock::queueTransform (transformation_t *transform)
{
    block_queue_transform (self, transform);
    
}

///
//  Self test of this class.
void QBlock::test (bool verbose)
{
    block_test (verbose);
    
}
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
