/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "qsprk.h"

///
//  Copy-construct to return the proper wrapped c types
QDescriptor::QDescriptor (descriptor_t *self, QObject *qObjParent) : QObject (qObjParent)
{
    this->self = self;
}


///
//  Creates a new descriptor.
QDescriptor::QDescriptor (QObject *qObjParent) : QObject (qObjParent)
{
    this->self = descriptor_new ();
}

///
//  Destroy the descriptor.
QDescriptor::~QDescriptor ()
{
    descriptor_destroy (&self);
}

///
//  Self test of this class.
void QDescriptor::test (bool verbose)
{
    descriptor_test (verbose);
    
}
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
