/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#ifndef Q_DESCRIPTOR_H
#define Q_DESCRIPTOR_H

#include "qsprk.h"

class QT_SPRK_EXPORT QDescriptor : public QObject
{
    Q_OBJECT
public:

    //  Copy-construct to return the proper wrapped c types
    QDescriptor (descriptor_t *self, QObject *qObjParent = 0);

    //  Creates a new descriptor.
    explicit QDescriptor (QObject *qObjParent = 0);

    //  Destroy the descriptor.
    ~QDescriptor ();

    //  Self test of this class.
    static void test (bool verbose);

    descriptor_t *self;
};
#endif //  Q_DESCRIPTOR_H
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
