/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "qsprk.h"

///
//  Copy-construct to return the proper wrapped c types
QSprkDescriptor::QSprkDescriptor (sprk_descriptor_t *self, QObject *qObjParent) : QObject (qObjParent)
{
    this->self = self;
}


///
//  Creates a new descriptor.
QSprkDescriptor::QSprkDescriptor (QObject *qObjParent) : QObject (qObjParent)
{
    this->self = sprk_descriptor_new ();
}

///
//  Destroy the sprk_descriptor.
QSprkDescriptor::~QSprkDescriptor ()
{
    sprk_descriptor_destroy (&self);
}

///
//  Self test of this class.
void QSprkDescriptor::test (bool verbose)
{
    sprk_descriptor_test (verbose);
    
}
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
