/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#ifndef Q_SPRK_BLOCK_H
#define Q_SPRK_BLOCK_H

#include "qsprk.h"

class QT_SPRK_EXPORT QSprkBlock : public QObject
{
    Q_OBJECT
public:

    //  Copy-construct to return the proper wrapped c types
    QSprkBlock (sprk_block_t *self, QObject *qObjParent = 0);

    //  Creates a new block
    explicit QSprkBlock (const QString &blockId, QSprkDescriptor *descriptor, zlist_t *appliedTransforms, QObject *qObjParent = 0);

    //  Destroy the sprk_block.
    ~QSprkBlock ();

    //  Queue a transformation to be applied to this block.
    void queueTransform (QSprkTransform *transform);

    //  
    const QString getId ();

    //  Self test of this class.
    static void test (bool verbose);

    sprk_block_t *self;
};
#endif //  Q_SPRK_BLOCK_H
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
