/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "qsprk.h"

///
//  Copy-construct to return the proper wrapped c types
QSprkTransform::QSprkTransform (sprk_transform_t *self, QObject *qObjParent) : QObject (qObjParent)
{
    this->self = self;
}


///
//  Creates a new transformation.
QSprkTransform::QSprkTransform (QObject *qObjParent) : QObject (qObjParent)
{
    this->self = sprk_transform_new ();
}

///
//  Destroy the sprk_transform.
QSprkTransform::~QSprkTransform ()
{
    sprk_transform_destroy (&self);
}

///
//  Self test of this class.
void QSprkTransform::test (bool verbose)
{
    sprk_transform_test (verbose);
    
}
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
