/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#ifndef Q_SPRK_H
#define Q_SPRK_H

#include <QObject>
#include <QString>
#include <sprk.h>

#if defined(Q_OS_WIN)
#  if !defined(QT_SPRK_EXPORT) && !defined(QT_SPRK_IMPORT)
#    define QT_SPRK_EXPORT
#  elif defined(QT_SPRK_IMPORT)
#    if defined(QT_SPRK_EXPORT)
#      undef QT_SPRK_EXPORT
#    endif
#    define QT_SPRK_EXPORT __declspec(dllimport)
#  elif defined(QT_SPRK_EXPORT)
#    undef QT_SPRK_EXPORT
#    define QT_SPRK_EXPORT __declspec(dllexport)
#  endif
#else
#  define QT_SPRK_EXPORT
#endif

//  Opaque class structures to allow forward references
class QSprkCtx;
class QSprkDataset;
class QSprkBlock;
class QSprkBlockdata;
class QSprkDescriptor;
class QSprkTransform;
class QSprkBlockManager;

//  Public API classes
#include "qsprkctx.h"
#include "qsprkdataset.h"
#include "qsprkblock.h"
#include "qsprkblockdata.h"
#include "qsprkdescriptor.h"
#include "qsprktransform.h"
#include "qsprkblockmanager.h"

#endif //  Q_SPRK_H
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
