/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "qsprk.h"

///
//  Copy-construct to return the proper wrapped c types
QSprkBlockManager::QSprkBlockManager (sprk_block_manager_t *self, QObject *qObjParent) : QObject (qObjParent)
{
    this->self = self;
}


///
//  Create a new block manager
QSprkBlockManager::QSprkBlockManager (QObject *qObjParent) : QObject (qObjParent)
{
    this->self = sprk_block_manager_new ();
}

///
//  Destroy the block manager
QSprkBlockManager::~QSprkBlockManager ()
{
    sprk_block_manager_destroy (&self);
}

///
//  
QSprkBlockdata * QSprkBlockManager::readAndStoreBlock (const QString &blockId, QSprkBlock *blockRef)
{
    QSprkBlockdata *rv = new QSprkBlockdata (sprk_block_manager_read_and_store_block (self, blockId.toUtf8().data(), &blockRef->self));
    return rv;
}

///
//  
QSprkBlockdata * QSprkBlockManager::getBlock (const QString &blockId)
{
    QSprkBlockdata *rv = new QSprkBlockdata (sprk_block_manager_get_block (self, blockId.toUtf8().data()));
    return rv;
}

///
//  Self test of this class.
void QSprkBlockManager::test (bool verbose)
{
    sprk_block_manager_test (verbose);
    
}
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
