/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#ifndef Q_SPRK_BLOCKDATA_H
#define Q_SPRK_BLOCKDATA_H

#include "qsprk.h"

class QT_SPRK_EXPORT QSprkBlockdata : public QObject
{
    Q_OBJECT
public:

    //  Copy-construct to return the proper wrapped c types
    QSprkBlockdata (sprk_blockdata_t *self, QObject *qObjParent = 0);

    //  Create a new sprk_blockdata.
    explicit QSprkBlockdata (QSprkBlock *block, float*data, quint32 length, QObject *qObjParent = 0);

    //  Destroy the sprk_blockdata.
    ~QSprkBlockdata ();

    //  Queue a transformation to be applied to this block.
    void queueTransform (QSprkTransform *transform);

    //  
    QSprkDescriptor * descriptor ();

    //  Self test of this class.
    static void test (bool verbose);

    sprk_blockdata_t *self;
};
#endif //  Q_SPRK_BLOCKDATA_H
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
