/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "qsprk.h"

///
//  Copy-construct to return the proper wrapped c types
QSprkDataset::QSprkDataset (sprk_dataset_t *self, QObject *qObjParent) : QObject (qObjParent)
{
    this->self = self;
}


///
//  Destroy the sprk_dataset.
QSprkDataset::~QSprkDataset ()
{
    sprk_dataset_destroy (&self);
}

///
//  Checkpoints all blocks and their transformations across executors.
void QSprkDataset::checkpoint ()
{
    sprk_dataset_checkpoint (self);
    
}

///
//  Multiplies all values by the multiplier.
void QSprkDataset::mul (float multiplier)
{
    sprk_dataset_mul (self, multiplier);
    
}

///
//  Calculates the sum of all values in the dataset.
float QSprkDataset::sum ()
{
    float rv = sprk_dataset_sum (self);
    return rv;
}

///
//  Self test of this class.
void QSprkDataset::test (bool verbose)
{
    sprk_dataset_test (verbose);
    
}
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
