/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#ifndef Q_SPRK_CTX_H
#define Q_SPRK_CTX_H

#include "qsprk.h"

class QT_SPRK_EXPORT QSprkCtx : public QObject
{
    Q_OBJECT
public:

    //  Copy-construct to return the proper wrapped c types
    QSprkCtx (sprk_ctx_t *self, QObject *qObjParent = 0);

    //  Creates a new sprk context which facilitates communication with
    //  known executors.                                               
    explicit QSprkCtx (const QString &brokerUri, QObject *qObjParent = 0);

    //  Destroy the sprk_ctx.
    ~QSprkCtx ();

    //  Loads data located in given paths distributed across executors.
    QSprkDataset * loadDense (const QString &pathList, quint32 rowSize);

    //  Self test of this class.
    static void test (bool verbose);

    sprk_ctx_t *self;
};
#endif //  Q_SPRK_CTX_H
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
