/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#ifndef Q_SPRK_BLOCK_MANAGER_H
#define Q_SPRK_BLOCK_MANAGER_H

#include "qsprk.h"

class QT_SPRK_EXPORT QSprkBlockManager : public QObject
{
    Q_OBJECT
public:

    //  Copy-construct to return the proper wrapped c types
    QSprkBlockManager (sprk_block_manager_t *self, QObject *qObjParent = 0);

    //  Create a new block manager
    explicit QSprkBlockManager (QObject *qObjParent = 0);

    //  Destroy the block manager
    ~QSprkBlockManager ();

    //  
    sprk_blockdata_t * readAndStoreBlock (const QString &blockId, QSprkBlock *blockRef);

    //  
    sprk_blockdata_t * getBlock (const QString &blockId);

    //  Self test of this class.
    static void test (bool verbose);

    sprk_block_manager_t *self;
};
#endif //  Q_SPRK_BLOCK_MANAGER_H
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
