/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "qsprk.h"

///
//  Copy-construct to return the proper wrapped c types
QSprkBlockdata::QSprkBlockdata (sprk_blockdata_t *self, QObject *qObjParent) : QObject (qObjParent)
{
    this->self = self;
}


///
//  Create a new sprk_blockdata.
QSprkBlockdata::QSprkBlockdata (QSprkBlock *block, float*data, quint32 length, QObject *qObjParent) : QObject (qObjParent)
{
    this->self = sprk_blockdata_new (block->self, data, (uint32_t) length);
}

///
//  Destroy the sprk_blockdata.
QSprkBlockdata::~QSprkBlockdata ()
{
    sprk_blockdata_destroy (&self);
}

///
//  Queue a transformation to be applied to this block.
void QSprkBlockdata::queueTransform (QSprkTransform *transform)
{
    sprk_blockdata_queue_transform (self, transform->self);
    
}

///
//  
QSprkDescriptor * QSprkBlockdata::descriptor ()
{
    QSprkDescriptor *rv = new QSprkDescriptor (sprk_blockdata_descriptor (self));
    return rv;
}

///
//  Self test of this class.
void QSprkBlockdata::test (bool verbose)
{
    sprk_blockdata_test (verbose);
    
}
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
