/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#include "qsprk.h"

///
//  Copy-construct to return the proper wrapped c types
QTransformation::QTransformation (transformation_t *self, QObject *qObjParent) : QObject (qObjParent)
{
    this->self = self;
}


///
//  Creates a new transformation.
QTransformation::QTransformation (QObject *qObjParent) : QObject (qObjParent)
{
    this->self = transformation_new ();
}

///
//  Destroy the transformation.
QTransformation::~QTransformation ()
{
    transformation_destroy (&self);
}

///
//  Self test of this class.
void QTransformation::test (bool verbose)
{
    transformation_test (verbose);
    
}
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
