/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#ifndef Q_TRANSFORMATION_H
#define Q_TRANSFORMATION_H

#include "qsprk.h"

class QT_SPRK_EXPORT QTransformation : public QObject
{
    Q_OBJECT
public:

    //  Copy-construct to return the proper wrapped c types
    QTransformation (transformation_t *self, QObject *qObjParent = 0);

    //  Creates a new transformation.
    explicit QTransformation (QObject *qObjParent = 0);

    //  Destroy the transformation.
    ~QTransformation ();

    //  Self test of this class.
    static void test (bool verbose);

    transformation_t *self;
};
#endif //  Q_TRANSFORMATION_H
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
