/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "sprk.h"
#include "../../native/include/org_zeromq_sprk_SprkCtx.h"

JNIEXPORT jlong JNICALL
Java_org_zeromq_sprk_SprkCtx__1_1new (JNIEnv *env, jclass c, jstring broker_uri)
{
    char *broker_uri_ = (char *) (*env)->GetStringUTFChars (env, broker_uri, NULL);
    //  Disable CZMQ signal handling; allow Java to deal with it
    zsys_handler_set (NULL);
    jlong new_ = (jlong) (intptr_t) sprk_ctx_new (broker_uri_);
    (*env)->ReleaseStringUTFChars (env, broker_uri, broker_uri_);
    return new_;
}

JNIEXPORT void JNICALL
Java_org_zeromq_sprk_SprkCtx__1_1destroy (JNIEnv *env, jclass c, jlong self)
{
    sprk_ctx_destroy ((sprk_ctx_t **) &self);
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_sprk_SprkCtx__1_1loadDense (JNIEnv *env, jclass c, jlong self, jstring path_list, jint row_size)
{
    char *path_list_ = (char *) (*env)->GetStringUTFChars (env, path_list, NULL);
    jlong load_dense_ = (jlong) (intptr_t) sprk_ctx_load_dense ((sprk_ctx_t *) (intptr_t) self, path_list_, (uint32_t) row_size);
    (*env)->ReleaseStringUTFChars (env, path_list, path_list_);
    return load_dense_;
}

JNIEXPORT void JNICALL
Java_org_zeromq_sprk_SprkCtx__1_1test (JNIEnv *env, jclass c, jboolean verbose)
{
    sprk_ctx_test ((bool) verbose);
}

