/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "sprk.h"
#include "../../native/include/org_zeromq_sprk_SprkDataset.h"

JNIEXPORT jlong JNICALL
Java_org_zeromq_sprk_SprkDataset__1_1new (JNIEnv *env, jclass c, jlong context, jstring path_list)
{
    char *path_list_ = (char *) (*env)->GetStringUTFChars (env, path_list, NULL);
    //  Disable CZMQ signal handling; allow Java to deal with it
    zsys_handler_set (NULL);
    jlong new_ = (jlong) (intptr_t) sprk_dataset_new ((sprk_ctx_t *) (intptr_t) context, path_list_);
    (*env)->ReleaseStringUTFChars (env, path_list, path_list_);
    return new_;
}

JNIEXPORT void JNICALL
Java_org_zeromq_sprk_SprkDataset__1_1destroy (JNIEnv *env, jclass c, jlong self)
{
    sprk_dataset_destroy ((sprk_dataset_t **) &self);
}

JNIEXPORT void JNICALL
Java_org_zeromq_sprk_SprkDataset__1_1checkpoint (JNIEnv *env, jclass c, jlong self)
{
    sprk_dataset_checkpoint ((sprk_dataset_t *) (intptr_t) self);
}

JNIEXPORT void JNICALL
Java_org_zeromq_sprk_SprkDataset__1_1mul (JNIEnv *env, jclass c, jlong self, jfloat multiplier)
{
    sprk_dataset_mul ((sprk_dataset_t *) (intptr_t) self, (float) multiplier);
}

JNIEXPORT jfloat JNICALL
Java_org_zeromq_sprk_SprkDataset__1_1sum (JNIEnv *env, jclass c, jlong self)
{
    jfloat sum_ = (jfloat) sprk_dataset_sum ((sprk_dataset_t *) (intptr_t) self);
    return sum_;
}

JNIEXPORT void JNICALL
Java_org_zeromq_sprk_SprkDataset__1_1test (JNIEnv *env, jclass c, jboolean verbose)
{
    sprk_dataset_test ((bool) verbose);
}

