/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "sprk.h"
#include "../../native/include/org_zeromq_sprk_Block.h"

JNIEXPORT jlong JNICALL
Java_org_zeromq_sprk_Block__1_1new (JNIEnv *env, jclass c, jlong descriptor, jlong transformations)
{
    //  Disable CZMQ signal handling; allow Java to deal with it
    zsys_handler_set (NULL);
    jlong new_ = (jlong) (intptr_t) block_new ((descriptor_t *) (intptr_t) descriptor, (transformation_t *) (intptr_t) transformations);
    return new_;
}

JNIEXPORT void JNICALL
Java_org_zeromq_sprk_Block__1_1destroy (JNIEnv *env, jclass c, jlong self)
{
    block_destroy ((block_t **) &self);
}

JNIEXPORT void JNICALL
Java_org_zeromq_sprk_Block__1_1test (JNIEnv *env, jclass c, jboolean verbose)
{
    block_test ((bool) verbose);
}

