/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "sprk.h"
#include "../../native/include/org_zeromq_sprk_SprkCtx.h"

JNIEXPORT jlong JNICALL
Java_org_zeromq_sprk_SprkCtx__1_1new (JNIEnv *env, jclass c)
{
    //  Disable CZMQ signal handling; allow Java to deal with it
    zsys_handler_set (NULL);
    jlong new_ = (jlong) (intptr_t) sprk_ctx_new ();
    return new_;
}

JNIEXPORT void JNICALL
Java_org_zeromq_sprk_SprkCtx__1_1destroy (JNIEnv *env, jclass c, jlong self)
{
    sprk_ctx_destroy ((sprk_ctx_t **) &self);
}

JNIEXPORT void JNICALL
Java_org_zeromq_sprk_SprkCtx__1_1assignBlock (JNIEnv *env, jclass c, jlong self, jlong block)
{
    sprk_ctx_assign_block ((sprk_ctx_t *) (intptr_t) self, (sprk_block_t *) (intptr_t) block);
}

JNIEXPORT void JNICALL
Java_org_zeromq_sprk_SprkCtx__1_1dropBlock (JNIEnv *env, jclass c, jlong self, jlong block)
{
    sprk_ctx_drop_block ((sprk_ctx_t *) (intptr_t) self, (sprk_block_t *) (intptr_t) block);
}

JNIEXPORT void JNICALL
Java_org_zeromq_sprk_SprkCtx__1_1test (JNIEnv *env, jclass c, jboolean verbose)
{
    sprk_ctx_test ((bool) verbose);
}

