/*  =========================================================================
    sprk_transform - 

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

#ifndef SPRK_TRANSFORM_H_INCLUDED
#define SPRK_TRANSFORM_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif


//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT!
//  @warning Please edit the model at "api/sprk_transform.xml" to make changes.
//  @interface
//  Creates a new transformation.
SPRK_EXPORT sprk_transform_t *
    sprk_transform_new (void);

//  Destroy the sprk_transform.
SPRK_EXPORT void
    sprk_transform_destroy (sprk_transform_t **self_p);

//  Self test of this class.
SPRK_EXPORT void
    sprk_transform_test (bool verbose);
//  @end

#ifdef __cplusplus
}
#endif

#endif
