/*  =========================================================================
    sprk_descriptor - 

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

#ifndef SPRK_DESCRIPTOR_H_INCLUDED
#define SPRK_DESCRIPTOR_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif


//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT!
//  @warning Please edit the model at "api/sprk_descriptor.xml" to make changes.
//  @interface
//  Creates a new descriptor.
SPRK_EXPORT sprk_descriptor_t *
    sprk_descriptor_new (void);

//  Destroy the sprk_descriptor.
SPRK_EXPORT void
    sprk_descriptor_destroy (sprk_descriptor_t **self_p);

//  Self test of this class.
SPRK_EXPORT void
    sprk_descriptor_test (bool verbose);
//  @end

#ifdef __cplusplus
}
#endif

#endif
