/*  =========================================================================
    sprk - SPRK wrapper

    The MIT License (MIT)                                                         
                                                                                  
    Copyright (c) 2016 Matt Forbes                                                
                                                                                  
    Permission is hereby granted, free of charge, to any person obtaining a copy  
    of this software and associated documentation files (the "Software"), to deal 
    in the Software without restriction, including without limitation the rights  
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell     
    copies of the Software, and to permit persons to whom the Software is         
    furnished to do so, subject to the following conditions:                      
                                                                                  
    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.                               
                                                                                  
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
    SOFTWARE.                                                                     

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef SPRK_LIBRARY_H_INCLUDED
#define SPRK_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  SPRK version macros for compile-time API detection

#define SPRK_VERSION_MAJOR 0
#define SPRK_VERSION_MINOR 0
#define SPRK_VERSION_PATCH 0

#define SPRK_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define SPRK_VERSION \
    SPRK_MAKE_VERSION(SPRK_VERSION_MAJOR, SPRK_VERSION_MINOR, SPRK_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBSPRK_STATIC
#       define SPRK_EXPORT
#   elif defined LIBSPRK_EXPORTS
#       define SPRK_EXPORT __declspec(dllexport)
#   else
#       define SPRK_EXPORT __declspec(dllimport)
#   endif
#else
#   define SPRK_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _sprk_ctx_t sprk_ctx_t;
#define SPRK_CTX_T_DEFINED
typedef struct _sprk_dataset_t sprk_dataset_t;
#define SPRK_DATASET_T_DEFINED
typedef struct _sprk_msg_t sprk_msg_t;
#define SPRK_MSG_T_DEFINED


//  Public API classes
#include "sprk_ctx.h"
#include "sprk_dataset.h"
#include "sprk_msg.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
