/*  =========================================================================
    sprk_block_manager - 

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

#ifndef SPRK_BLOCK_MANAGER_H_INCLUDED
#define SPRK_BLOCK_MANAGER_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif


//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT!
//  @warning Please edit the model at "api/sprk_block_manager.xml" to make changes.
//  @interface
//  Create a new block manager
SPRK_EXPORT sprk_block_manager_t *
    sprk_block_manager_new (void);

//  Destroy the block manager
SPRK_EXPORT void
    sprk_block_manager_destroy (sprk_block_manager_t **self_p);

//  
SPRK_EXPORT sprk_blockdata_t *
    sprk_block_manager_read_and_store_block (sprk_block_manager_t *self, const char *block_id, sprk_block_t **block_ref);

//  
SPRK_EXPORT sprk_blockdata_t *
    sprk_block_manager_get_block (sprk_block_manager_t *self, const char *block_id);

//  Self test of this class.
SPRK_EXPORT void
    sprk_block_manager_test (bool verbose);
//  @end

#ifdef __cplusplus
}
#endif

#endif
